default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 10.0   # rad/s
    has_acceleration_limits: true
    max_acceleration: 20.0   # rad/s^2
  joint2:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 20.0
  slider_actuator:
    has_velocity_limits: true
    max_velocity: 0.2   # m/s (prismatic joint, much smaller)
    has_acceleration_limits: true
    max_acceleration: 0.5   # m/s^2